### ISSUE TITLE
File won't download if there's a non-ASCII character in the title

### ISSUE THREAD

**Issue by SiphoxR** [Terracrow/lyd#1]
When you try to download a video from youtube and the video's title has a non-ASCII character in it, the command prompt will close itself and the file won't download

**Comment by SiphoxR** [comment]
By the way here's the error : https://www.toptal.com/developers/hastebin/duwiluliva.less

**Comment by Terracrow** [comment]
Thank you for informing me of this error, this project has been abandoned for ages so I do not intend to work hard on it for long, I will surely make a better, more developed and compact version of it, but I do not intend to keep this one any longer that long.
_Terra_
